### ISSUE TITLE
Install Kafka using Docker with Compose

### ISSUE THREAD

**Issue by apoorvpandey-ap** [apoorvpandey-ap/Docker#1]
## We cover 
- [x] [docker --version](https://github.com/apoorvpandey-ap/Docker/issues/1#issuecomment-1066628991)
- [x] [docker-compose --version](https://github.com/apoorvpandey-ap/Docker/issues/1#issuecomment-1066631099)
- [x] [docker images](https://github.com/apoorvpandey-ap/Docker/issues/1#issuecomment-1066639052)
- [x] [docker-compose -f docker-compose.yml up -d](https://github.com/apoorvpandey-ap/Docker/issues/1#issuecomment-1066640596)
- [x] [docker ps](https://github.com/apoorvpandey-ap/Docker/issues/1#issuecomment-1066653706)
- [x] [docker exec -it ContainerId /bin/sh](https://github.com/apoorvpandey-ap/Docker/issues/1#issuecomment-1066659133)
- [x][ kafka-topics.sh --create --topic library-events --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1](https://github.com/apoorvpandey-ap/Docker/issues/1#issuecomment-1066659133)

**Comment by apoorvpandey-ap** [comment]
### **Step-1** Check docker version 
`docker --version`
#
![image](https://user-images.githubusercontent.com/66588814/158156359-e8854c89-a4ee-4493-a104-99492e0f28e0.png)

**Comment by apoorvpandey-ap** [comment]
### **Step-2** Check docker compose version
`docker-compose --version`
#
![image](https://user-images.githubusercontent.com/66588814/158156804-203a85dd-9b54-4410-b97e-0922d7146486.png)

**Comment by apoorvpandey-ap** [comment]
### **Step-3** Check  docker images
`docker --version`
#
![image](https://user-images.githubusercontent.com/66588814/158158137-e2cb608b-1a7d-45c7-96b2-c433f1e93f3d.png)

**Comment by apoorvpandey-ap** [comment]
### **Step-4** UP the docker compose
`docker-compose -f docker-compose.yml up -d`
#
## YML file save as `docker-compose`
```
version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kakfa
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
```
#
![image](https://user-images.githubusercontent.com/66588814/158158471-f768568f-8948-41ea-a04c-d5dab7ee819b.png)

**Comment by apoorvpandey-ap** [comment]
### **Step-5** Check docker ps 
`docker ps`
#
![image](https://user-images.githubusercontent.com/66588814/158160328-49dfb292-8cb2-4091-bbe9-b55d64eb09c6.png)

**Comment by apoorvpandey-ap** [comment]
### **Step-6** Connet with Shell
```
docker exec -it ContainerId /bin/sh
cd opt
cd bitnami
cd kafka
```
#
![image](https://user-images.githubusercontent.com/66588814/158160986-fc36ecf0-0aa3-4eba-8c17-f4836485d1f7.png)

**Comment by apoorvpandey-ap** [comment]
### **Step-7** Check docker version 
`kafka-topics.sh --create --topic library-events --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1`
